#pragma once

#ifdef ESP_PLATFORM
#include "sdkconfig.h"
#endif

#ifndef CONFIG_BOARD_SEEED_XIAO_ESP32S3
#define CONFIG_BOARD_SEEED_XIAO_ESP32S3 0
#endif

#if (CONFIG_BOARD_XINLUCITY_ESP32S3_NANO || CONFIG_BOARD_SEEED_XIAO_ESP32S3) && CONFIG_IDF_TARGET_ESP32S3
#define BOARD_HARDWARE_SUPPORTED 1
#else
#define BOARD_HARDWARE_SUPPORTED 0
#endif

#define BOARD_WAKE_GPIO 0
#define BOARD_POWER_DEFAULT_IDLE_MINUTES 0

#if CONFIG_BOARD_SEEED_XIAO_ESP32S3
#define BOARD_STATUS_GPIO 21
#define BOARD_STATUS_SLEEP_MODE GPIO_MODE_OUTPUT
#else
#define BOARD_STATUS_GPIO 48
#define BOARD_STATUS_SLEEP_MODE GPIO_MODE_DISABLE
#endif
